import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Navbar from "../../components/Navbar/Navbar";
import useAuth from "../../hooks/useAuth";
import styles from "../../styles/Direct.module.css";
import { HiOutlinePencilAlt } from "react-icons/hi";
import ChatItem from "../../components/ChatItem/ChatItem";
import InfoIcon from "../../components/Icons/InfoIcon";
function Direct() {
  const [logout, setLogout] = React.useState(false);
  const [newPost, setNewPost] = React.useState(false);
  const [paddingTop] = React.useState(0);
  const [paddingBottom, setPaddingBottom] = React.useState(0);
  const [chat, setChat] = React.useState(false);
  const router = useRouter();
  const user = useAuth();

  const handleScroll = (e) => {
    console.log(e.target.scrollTop);
    console.log(e.target.scrollHeight);
    console.log(e.target.clientHeight);
    setPaddingBottom(
      e.target.scrollHeight - e.target.scrollTop * 2 - e.target.clientHeight
    );
  };

  return (
    <div>
      <Head>
        <title>InstaNext | Direct</title>
        <meta
          name="description"
          content="Generated by create next app & firebase"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        setLogout={setLogout}
        user={user && user}
        setNewPost={setNewPost}
      />

      <div className={styles.direct__body}>
        <div className={styles.direct__body_container}>
          <div className={styles.chats_container}>
            <div className={styles.chat_header}>
              <div className={styles.chat_header_container}>
                <div className={styles.blank_box}></div>
                <div className={styles.chat_author}>
                  <div className={styles.chat_author_container}>
                    <button>
                      Sumit Bighaniya
                      <span>
                        <svg
                          aria-label="Down Chevron Icon"
                          className="_8-yf5 "
                          color="#262626"
                          fill="#262626"
                          height="20"
                          role="img"
                          viewBox="0 0 24 24"
                          width="20"
                        >
                          <path d="M21 17.502a.997.997 0 01-.707-.293L12 8.913l-8.293 8.296a1 1 0 11-1.414-1.414l9-9.004a1.03 1.03 0 011.414 0l9 9.004A1 1 0 0121 17.502z"></path>
                        </svg>
                      </span>
                    </button>
                  </div>
                </div>
                <button className={styles.new_chat_btn}>
                  <HiOutlinePencilAlt />
                </button>
              </div>
            </div>
            <div
              className={styles.chats_wrapper}
              onScroll={handleScroll}
              style={{
                paddingBottom: paddingBottom,
              }}
            >
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
              <ChatItem />
            </div>
          </div>
          <div className={styles.chat_body}>
            {chat && (
              <div className={styles.chat_body_header}>
                <div className={styles.chat_body_header_wrap}>
                  <div className={styles.chat_body_header_content}>
                    <div className={styles.chat_header_primary}>
                      <div className={styles.chat_primary_content}>
                        <div className={styles.chat_primary_user_avatar}></div>
                        <div className={styles.current_chat_meta}>
                          <button>
                            <div className={styles.current_chat_content}>
                              <h3 className={styles.chat_user_name}>
                                Ravi Ranjan Jha
                              </h3>
                              <p className="text-sm text-gray-600">
                                Active now
                              </p>
                            </div>
                          </button>
                        </div>
                      </div>
                    </div>
                    <div className={styles.chat_header_controls}>
                      <button>
                        <InfoIcon />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            )}

            <div className={styles.chat_body_empty}>
              <div className={styles.empty_chat_icon}>
                <svg
                  aria-label="Direct"
                  className="_8-yf5 "
                  color="#262626"
                  fill="#262626"
                  height="96"
                  role="img"
                  viewBox="0 0 96 96"
                  width="96"
                >
                  <circle
                    cx="48"
                    cy="48"
                    fill="none"
                    r="47"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                  ></circle>
                  <line
                    fill="none"
                    stroke="currentColor"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    x1="69.286"
                    x2="41.447"
                    y1="33.21"
                    y2="48.804"
                  ></line>
                  <polygon
                    fill="none"
                    points="47.254 73.123 71.376 31.998 24.546 32.002 41.448 48.805 47.254 73.123"
                    stroke="currentColor"
                    strokeLinejoin="round"
                    strokeWidth="2"
                  ></polygon>
                </svg>
              </div>
              <div className={styles.empty_chat_title}>
                <h3>Your messages</h3>
              </div>
              <div className={styles.empty_chat_subtitle}>
                <h6>Send private photos and messages to a friend or group.</h6>
              </div>
              <button className={styles.new_chat_btn_secondary}>
                <span>Send message</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Direct;
