import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Navbar from "../../components/Navbar/Navbar";
import { RiSettingsLine } from "react-icons/ri";
import styles from "./Profile.module.css";
import { BsFillHeartFill } from "react-icons/bs";
import { FaCommentDots, FaPlay } from "react-icons/fa";

function ProfilePost({ image, type }) {
  return (
    <div className={`${styles.profile_post_item} cursor-pointer`}>
      <img src={image} alt="" />
      <div className={styles.post_overlay}>
        <div className={styles.post_meta_info}>
          <span>
            {type === "photo" ? <BsFillHeartFill /> : <FaPlay />}
            <p>55</p>
          </span>
          <span>
            <FaCommentDots />
            <p>0</p>
          </span>
        </div>
      </div>
    </div>
  );
}
function User() {
  const router = useRouter();
  const { uid } = router.query;
  const [tab, setTab] = React.useState(0);
  const mypost = [];
  let user = "sumit";
  const posts = [
    {
      id: 1,
      type: "video",
      author: "sumit",
      thumb:
        "https://images.unsplash.com/photo-1549570652-97324981a6fd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=385&q=80",
    },
    {
      id: 2,
      type: "photo",
      author: "rahul",
      thumb:
        "https://images.unsplash.com/photo-1581599129568-e33151627628?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    },
    {
      id: 3,
      type: "video",
      author: "sumit",
      thumb:
        "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
    },
  ];

  const saved_posts = [
    {
      id: 1,
      type: "video",
      author: "sumit",
      thumb:
        "https://images.unsplash.com/photo-1549570652-97324981a6fd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=385&q=80",
    },
    {
      id: 2,
      type: "photo",
      author: "rahul",
      thumb:
        "https://images.unsplash.com/photo-1581599129568-e33151627628?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    },
  ];

  const tagged_posts = [
    {
      id: 2,
      type: "photo",
      author: "rahul",
      thumb:
        "https://images.unsplash.com/photo-1581599129568-e33151627628?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.profile_body}>
        <div className={styles.porfile_header}>
          <div className={styles.profile_user_avatar}>
            <img src="https://randomuser.me/api/portraits/men/36.jpg" alt="" />
          </div>
          <div className={styles.profile_user_info}>
            <div className={styles.user_profile_first}>
              <h3>sumitbighaniya</h3>
              <button className={`${styles.edit_btn} text-sm`}>
                Edit Profile
              </button>
              <button className={styles.setting_btn}>
                <RiSettingsLine />
              </button>
            </div>
            <div className={styles.user_profile_second}>
              <span className={styles.user_info_item}>
                <strong>16</strong>
                <p>posts</p>
              </span>
              <span className={styles.user_info_item}>
                <strong>1,226</strong>
                <p>followers</p>
              </span>
              <span className={styles.user_info_item}>
                <strong>324</strong>
                <p>following</p>
              </span>
            </div>
            <div className="user-profile-third">
              <h3 className="font-semibold">Sumit Bighaniya</h3>
              <span className="text-gray-600">Education</span>
              <p>MERN Stack Developer</p>
              <a href="#" className="text-sky-600">
                linktr.ee/sumitkumarbig
              </a>
            </div>
          </div>
        </div>
        <div className={styles.profile_toggle}>
          <div className={styles.toggle_body}>
            <div
              className={`${styles.toggle_item} ${
                tab === 0 && styles.toogle_item_enable
              } cursor-pointer`}
              onClick={() => setTab(0)}
            >
              <span>
                <img src="/assets/grid.svg" alt="" />
              </span>
              <span>POSTS</span>
            </div>
            <div
              className={`${styles.toggle_item} cursor-pointer ${
                tab === 1 && styles.toogle_item_enable
              }`}
              onClick={() => setTab(1)}
            >
              <span>
                <img src="/assets/save_icon.svg" alt="" />
              </span>
              <span>SAVED</span>
            </div>
            <div
              className={`${styles.toggle_item} ${
                tab === 2 && styles.toogle_item_enable
              } cursor-pointer`}
              onClick={() => setTab(2)}
            >
              <span>
                <img src="/assets/tag.svg" alt="" />
              </span>
              <span>TAGGED</span>
            </div>
          </div>
        </div>
        <div className={styles.profile_posts}>
          {tab === 0 &&
            posts
              .filter((item) => item.author === user)
              .map((post, i) => {
                return (
                  <ProfilePost key={i} image={post.thumb} type={post.type} />
                );
              })}
          {tab === 1 &&
            saved_posts.map((post, i) => {
              return (
                <ProfilePost key={i} image={post.thumb} type={post.type} />
              );
            })}

          {tab === 2 &&
            tagged_posts.map((post, i) => {
              return (
                <ProfilePost key={i} image={post.thumb} type={post.type} />
              );
            })}
        </div>
      </div>
    </div>
  );
}

export default User;
